### ISSUE TITLE
Can't read data generated from waters instrument after MSconvert

### ISSUE THREAD

**Issue by OmarAshkar** [wkumler/RaMS#40]
Hello, 

I has waters raw file that I have converted using MSconvert. I converted it to mzML, but can't open it in R. It reads find with seeMS.
It just return empty dataframe.

Please let me know if I am missing something.
[2024-04-15.zip](https://github.com/user-attachments/files/16821495/2024-04-15.zip)

Thanks,
Omar

**Comment by wkumler** [comment]
Hi @OmarAshkar, thanks for opening an issue. It looks like the file is the result of an SRM experiment where the data's reported in chromatograms. Did you enable chromatogram reading by including "chroms" in the `grab_what` argument? The snippet of code below seems to work fine for me but maybe you've got different goals or expectations for what the file should include, in which case I'd love to hear more about what your workflow looks like.

```r
library(RaMS)
msdata <- grabMSdata("~/../Downloads/2024-04-15/2024-04-15.mzML", grab_what = "chroms")
qplotMS1data(msdata$chroms[chrom_type=="TIC"])
```

![image](https://github.com/user-attachments/assets/41ec5912-4b49-453f-bb3c-476ec6069f6d)

```R
qplotMS1data(msdata$chroms[chrom_type=="SRM SIC Q1=112.044 Q3=67.9799 function=1 offset=2"])
```

![image](https://github.com/user-attachments/assets/4542cf9a-6a8b-4d2d-9ba3-512294d34721)
